### ISSUE TITLE
Screen not displaying properly.

### ISSUE THREAD

**Issue by Ben-Russell** [citronneur/mstsc.js#2]
I'm getting a screen like:

![h7v7dnu](https://cloud.githubusercontent.com/assets/4826551/8580533/06149c0e-2570-11e5-8912-82ba42892f1d.png)

The screen slowly fills over time.

Attempting from:
Windows 8.1; Chrome 43.0.2357.132 m (64-bit)

Server:
CentOS 7.1.1503
NodeJS v0.12.6

Machine trying to reach:
Windows 8.1

Seems to connect fine from the node messages on the server. I have also tried in Firefox. Would it have to do with the "host" machine having multiple monitors? Let me know if you need any other data.

**Comment by citronneur** [comment]
Hello,

Can you try to checkout the hotfix branch and show me log of your browser console : 
[mstsc.js] bitmap update bpp : ?

git clone https://github.com/citronneur/mstsc.js
cd mstsc.js
checkout hotfix
npm install
node server.js

go to http://localhost:9250 and activate your debug console
Thanks

**Comment by Ben-Russell** [comment]
It constantly logs:

`client.js:154 [mstsc.js] bitmap update bpp : 32`

**Comment by citronneur** [comment]
Ok i will fix it today!!!

**Comment by citronneur** [comment]
This fix in last release 0.2.3

**Comment by Ben-Russell** [comment]
Thanks, works now!
