### ISSUE TITLE
[node-rdpjs] ERROR:     NODE_RDP_PROTOCOL_X224_NEG_FAILURE()

### ISSUE THREAD

**Issue by BadFishy** [citronneur/mstsc.js#37]

**Comment by BadFishy** [comment]
In order to overcome the error " NODE_RDP_PROTOCOL_X224_NEG_FAILURE()", ensure that Network Level Authentication is disabled for RDP under Control Panel->System->Remote settings

**Comment by BadFishy** [comment]
reference: https://www.ezeelogin.com/kb/article/node_rdp_protocol_x224_neg_failure-184.html

**Comment by chimyking** [comment]
what's the value of domain? I don't know how to fill it。
