### ISSUE TITLE
Please update bignum library to new version

### ISSUE THREAD

**Issue by Giancarlo1974** [citronneur/mstsc.js#5]
Hi.

I lost many hours to compile the library.
I successfully configured the development environment by following this guide:

http://www.serverpals.com/blog/building-using-node-gyp-with-visual-studio-express-2015-on-windows-10-pro-x64

If I run the command:
npm install node-rdp
npm install successfully version
bignum@0.11.0

But if I used the command:
npm install mstsc.js
npm want to install bignum@0.10.2

105 silly resolveWithNewModule bignum@0.10.2 checking installable status
106 silly cache add args ['bignum@^0.10.2', null]

and does not compile :-(

How can I force mstsc.js to use the new version of the library?
Can you help me?

**Comment by fscardua** [comment]
Same problem here.

**Comment by xila76** [comment]
+1 :+1:
