### ISSUE TITLE
Support for node 4

### ISSUE THREAD

**Issue by nono** [citronneur/mstsc.js#6]
Hello,

I'm from the Cozy Cloud team. We planned to support node 4 in the sort term and we offer help for community application to do that too.

mstsc.js can't be installed with node 4 currently because it depends on node-rdpjs@0.2.1 that comes with bignum@0.10.2. A fix for node 4 support has landed on node-rdpjs master branch (https://github.com/citronneur/node-rdpjs/commit/de7113aa66b09e0d9ca47cf387688134ece21c9d).

I think all you have to do is release a new version of node-rdpjs and use it in mstsc.js. And if you want help, ask me: this issue is mostly for that, offering my help.

**Comment by frankrousseau** [comment]
Ping @citronneur. Do you want we open Pull Requests to fix that problem?

**Comment by chris25640** [comment]
Hi,

Same problem, can't install MSTSC.JS because i use node v4, please can you fix it?

Thanks

**Comment by citronneur** [comment]
Ok for me! Happy to be in cozy cloud store ;-)

**Comment by chris25640** [comment]
Thanks man ! Work perfectly
