### ISSUE TITLE
Custom Port

### ISSUE THREAD

**Issue by k1ngf15h3r** [citronneur/mstsc.js#8]
Tested mstsc.js inside of cozy, but I am not able to specify a custom port in the ip address field, had many cases where this should be needed to get a connection. Is there a trick or a workaround to enable it?

**Comment by citronneur** [comment]
Hi!

Use IP:Port synthax.

**Comment by Dhiraj3089** [comment]
it's not working with custom port, i also tried with **IP:PORT** syntax but it's appending port  **3389** at end

**Comment by sergzhukov** [comment]
Yes, confirm, according to logs ip:port syntax is not correct, added ":3389" to any url string. Please, add custom port possibility - this is widespread practice in the world due "rdp worms" activity. Otherwise this application is completely useless if not in local network

**Comment by citronneur** [comment]
ok not possible, i will do for next release

**Comment by tremez** [comment]
When i provide custom port in the client.js, it tells 
[node-rdpjs] ERROR:	NODE_RDP_PROTOCOL_X224_NEG_FAILURE()
When i use default port - all is ok

**Comment by tremez** [comment]
// emit infos event
			this.socket.emit('infos', {
				ip : ip,
				port : 43389,
				screen : {
					width : this.canvas.width,
					height : this.canvas.height
				},
				domain : domain,
				username : username,
				password : password,
				locale : Mstsc.locale()
			});

**Comment by hktalent** [comment]
@citronneur @sergzhukov @Dhiraj3089 @k1ngf15h3r @ianchanning 
## client.js
```
// emit infos event
			this.socket.emit('infos', {
				ip : ip, 
				port : port, 
				screen : { 
					width : this.canvas.width, 
					height : this.canvas.height 
				}, 
				domain : domain, 
				username : username, 
				password : password, 
				locale : Mstsc.locale()
			});
```
### html
```
function connect (_t) {
    var a = _t.elements,
      ip = a['inputIpAddress'].value, 
      domain = a['inputDomain'].value, 
      username = a['inputUsername'].value, 
      password = a['inputPassword'].value,
      port = a['port'].value;
    Mstsc.$("main").style.display = 'none';
    var canvas = Mstsc.$("myCanvas");
    canvas.style.display = 'inline';
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    client.connect(ip, domain, username, password,port, function (err) {
        //Mstsc.$("myCanvas").style.display = 'none';
        Mstsc.$("main").style.display = 'inline';
    });
}

<form class="form-signin"  onSubmit="connect(this);return false;">
			<label for="inputIpAddress" class="sr-only">IP Address</label>
			<input type="text" id="inputIpAddress" class="form-control" placeholder="IP Address" required autofocus>
      <label for="port" class="sr-only">Port</label>
			<input type="text" id="port" value="3389" class="form-control" placeholder="Port" required>
			<label for="inputDomain" class="sr-only">Domain</label>
			<input type="text" id="inputDomain" class="form-control" placeholder="Domain">
			<label for="inputUsername" class="sr-only">Username</label>
			<input type="text" id="inputUsername" class="form-control" placeholder="Username">
			<label for="inputPassword" class="sr-only">Password</label>
			<input type="password" id="inputPassword" class="form-control" placeholder="Password">
			<button class="btn btn-lg btn-primary btn-block" type="submit" style="background-color: #34A6FF; border-color: #34A6FF">Connect</button>
		</form>
```

**Comment by wzfxue** [comment]
client.js
		this.socket.emit('infos', {
				**ip : ip.indexOf(":")>-1 ? ip.split(":")[0] : ip, 
				port : ip.indexOf(":")>-1 ? parseInt(ip.split(":")[1]) : 3389,** 
				screen : { 
					width : this.canvas.width, 
					height : this.canvas.height 
				},
				domain : domain, 
				username : username, 
				password : password, 
				locale : Mstsc.locale()
			});

--------------------
ip:port
